### ISSUE TITLE
[UML] Diagramme de classe incorrect

### ISSUE THREAD

**Issue by droumanet** [LucasPerbet/Pharmacie_SAUTHEUZ#2]
Sauf si votre application aura une vue Supprimer permettant de supprimer à la fois une ordonnance, un patient, un médecin, un médicament, une mutuelle et une pathologie (et ainsi pour les autres éléments du CRUD), le diagramme est faux.
Il faux regrouper par vue/écran 😉

**Comment by LucasPerbet** [comment]
Diagramme d'utilisation mis-à-jour dans le commit référencé.
